-- Intentionally empty.
--
-- Local and disposable development environments are seeded exclusively from
-- ./seeds/local-only.sql as configured in config.toml. Never place production
-- snapshots, real user records, access tokens, join codes, or student data in
-- this tracked file.
