-- AUD-035: plugin_data remains unreachable to browser roles, including new
-- objects created after this ledger point.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(10);

SELECT extensions.ok(
  NOT has_schema_privilege('anon', 'plugin_data', 'USAGE'),
  'anon has no plugin_data schema usage'
);
SELECT extensions.ok(
  NOT has_schema_privilege('authenticated', 'plugin_data', 'USAGE'),
  'authenticated has no plugin_data schema usage'
);
SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_proc AS function_record
    JOIN pg_namespace AS namespace ON namespace.oid = function_record.pronamespace
    WHERE namespace.nspname = 'plugin_data'
      AND has_function_privilege('anon', function_record.oid, 'EXECUTE')
  ),
  0::bigint,
  'anon cannot execute any plugin_data function'
);
SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_proc AS function_record
    JOIN pg_namespace AS namespace ON namespace.oid = function_record.pronamespace
    WHERE namespace.nspname = 'plugin_data'
      AND has_function_privilege('authenticated', function_record.oid, 'EXECUTE')
  ),
  0::bigint,
  'authenticated cannot execute any plugin_data function'
);
SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_default_acl AS default_acl
    JOIN pg_namespace AS namespace ON namespace.oid = default_acl.defaclnamespace
    CROSS JOIN LATERAL aclexplode(default_acl.defaclacl) AS acl
    LEFT JOIN pg_roles AS grantee ON grantee.oid = acl.grantee
    WHERE namespace.nspname = 'plugin_data'
      AND (acl.grantee = 0 OR grantee.rolname IN ('anon', 'authenticated'))
  ),
  0::bigint,
  'plugin_data has no browser-facing default ACL entries'
);

CREATE TABLE plugin_data.aud_035_future_table (id bigint GENERATED BY DEFAULT AS IDENTITY);
CREATE FUNCTION plugin_data.aud_035_future_function()
RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;

SELECT extensions.ok(
  NOT has_table_privilege('anon', 'plugin_data.aud_035_future_table', 'SELECT,INSERT,UPDATE,DELETE'),
  'anon receives no future table privilege'
);
SELECT extensions.ok(
  NOT has_table_privilege('authenticated', 'plugin_data.aud_035_future_table', 'SELECT,INSERT,UPDATE,DELETE'),
  'authenticated receives no future table privilege'
);
SELECT extensions.ok(
  NOT has_sequence_privilege('authenticated', 'plugin_data.aud_035_future_table_id_seq', 'USAGE'),
  'authenticated receives no future sequence privilege'
);
SELECT extensions.ok(
  NOT has_function_privilege('anon', 'plugin_data.aud_035_future_function()', 'EXECUTE'),
  'anon receives no future function execution'
);
SELECT extensions.ok(
  NOT has_function_privilege('authenticated', 'plugin_data.aud_035_future_function()', 'EXECUTE'),
  'authenticated receives no future function execution'
);

SELECT * FROM extensions.finish();
ROLLBACK;
