-- AUD-042: plugin_data is unreachable from the browser roles, including for
-- objects a later migration creates, while service-role access is preserved.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT extensions.plan(17);

WITH client_roles(role_name) AS (
  VALUES ('anon'), ('authenticated')
)
SELECT extensions.ok(
  NOT has_schema_privilege(role_name, 'plugin_data', 'USAGE'),
  format('%s has no plugin_data schema usage', role_name)
)
FROM client_roles;

SELECT extensions.ok(
  has_schema_privilege('service_role', 'plugin_data', 'USAGE'),
  'service_role keeps the server-side plugin_data path'
);

SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_class AS relation
    JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
    CROSS JOIN unnest(ARRAY['anon'::text, 'authenticated'::text]) AS client(role_name)
    WHERE namespace.nspname = 'plugin_data'
      AND relation.relkind IN ('r', 'p', 'v', 'm', 'f')
      AND has_table_privilege(
        client.role_name,
        relation.oid,
        'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'
      )
  ),
  0::bigint,
  'no browser role holds a privilege on any existing plugin_data relation'
);

SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_class AS relation
    JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
    CROSS JOIN unnest(ARRAY['anon'::text, 'authenticated'::text]) AS client(role_name)
    WHERE namespace.nspname = 'plugin_data'
      AND relation.relkind = 'S'
      AND has_sequence_privilege(client.role_name, relation.oid, 'USAGE,SELECT,UPDATE')
  ),
  0::bigint,
  'no browser role holds a privilege on any existing plugin_data sequence'
);

SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_proc AS routine
    JOIN pg_namespace AS namespace ON namespace.oid = routine.pronamespace
    CROSS JOIN unnest(ARRAY['anon'::text, 'authenticated'::text, 'public'::text]) AS client(role_name)
    WHERE namespace.nspname = 'plugin_data'
      AND has_function_privilege(client.role_name, routine.oid, 'EXECUTE')
  ),
  0::bigint,
  'no browser role can execute any existing plugin_data routine'
);

SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_default_acl AS default_acl
    JOIN pg_namespace AS namespace ON namespace.oid = default_acl.defaclnamespace
    CROSS JOIN LATERAL aclexplode(default_acl.defaclacl) AS acl
    LEFT JOIN pg_roles AS grantee ON grantee.oid = acl.grantee
    WHERE namespace.nspname = 'plugin_data'
      AND (acl.grantee = 0 OR grantee.rolname IN ('anon', 'authenticated'))
  ),
  0::bigint,
  'plugin_data has no browser-facing default ACL entries'
);

SELECT extensions.is(
  (
    SELECT count(DISTINCT owners.role_name)
    FROM (
      SELECT pg_get_userbyid(relation.relowner) AS role_name
      FROM pg_class AS relation
      JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
      WHERE namespace.nspname = 'plugin_data'
      UNION
      SELECT pg_get_userbyid(routine.proowner)
      FROM pg_proc AS routine
      JOIN pg_namespace AS namespace ON namespace.oid = routine.pronamespace
      WHERE namespace.nspname = 'plugin_data'
    ) AS owners
    WHERE NOT EXISTS (
      SELECT 1
      FROM pg_default_acl AS default_acl
      JOIN pg_namespace AS namespace ON namespace.oid = default_acl.defaclnamespace
      WHERE namespace.nspname = 'plugin_data'
        AND pg_get_userbyid(default_acl.defaclrole) = owners.role_name
    )
  ),
  0::bigint,
  'every role that owns plugin_data objects has a reviewed default ACL entry'
);

-- Objects created after this ledger point inherit the closed defaults.
CREATE TABLE plugin_data.aud_042_future_table (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
CREATE FUNCTION plugin_data.aud_042_future_function()
RETURNS integer LANGUAGE sql IMMUTABLE SET search_path = '' AS $$ SELECT 1 $$;

WITH client_roles(role_name) AS (
  VALUES ('anon'), ('authenticated')
)
SELECT extensions.ok(
  NOT has_table_privilege(
    role_name,
    'plugin_data.aud_042_future_table',
    'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'
  ),
  format('%s inherits no privilege on a new plugin_data table', role_name)
)
FROM client_roles;

WITH client_roles(role_name) AS (
  VALUES ('anon'), ('authenticated')
)
SELECT extensions.ok(
  NOT has_sequence_privilege(
    role_name,
    'plugin_data.aud_042_future_table_id_seq',
    'USAGE,SELECT,UPDATE'
  ),
  format('%s inherits no privilege on a new plugin_data sequence', role_name)
)
FROM client_roles;

-- PostgreSQL's built-in global default still puts EXECUTE for PUBLIC on a new
-- function, and a per-schema default cannot revoke a globally granted default.
-- So the routine must name no browser role, and schema USAGE denial must make
-- the residual PUBLIC bit unreachable in practice.
SELECT extensions.is(
  (
    SELECT count(*)
    FROM pg_proc AS routine
    CROSS JOIN LATERAL aclexplode(routine.proacl) AS acl
    WHERE routine.oid = 'plugin_data.aud_042_future_function()'::regprocedure
      AND acl.grantee IN ('anon'::regrole, 'authenticated'::regrole)
  ),
  0::bigint,
  'a new plugin_data routine names no browser role in its own grants'
);

SET LOCAL ROLE anon;

SELECT extensions.throws_ok(
  $$SELECT plugin_data.aud_042_future_function()$$,
  '42501', NULL, 'anon cannot call a new plugin_data routine'
);

SELECT extensions.throws_ok(
  $$SELECT 1 FROM plugin_data.aud_042_future_table$$,
  '42501', NULL, 'anon cannot read a new plugin_data table'
);

RESET ROLE;
SET LOCAL ROLE authenticated;

SELECT extensions.throws_ok(
  $$SELECT plugin_data.aud_042_future_function()$$,
  '42501', NULL, 'authenticated cannot call a new plugin_data routine'
);

SELECT extensions.throws_ok(
  $$SELECT 1 FROM plugin_data.aud_042_future_table$$,
  '42501', NULL, 'authenticated cannot read a new plugin_data table'
);

RESET ROLE;

SELECT * FROM extensions.finish();
ROLLBACK;
