import consoleEvents from "./log-console-events.json";

// Reviewed static event names. Unknown messages are replaced before export.
export const SAFE_LOG_MESSAGES = new Set<string>([
  ...consoleEvents,
  "Worker monitoring receipt unavailable",
  "Data export cron failed",
  "Data export artifact cleanup unconfirmed",
  "Moderation email attempt",
  "Moderation contact lookup failed",
  "Moderation notification preferences could not be read",
  "Moderation notification write failed",
  "CSF post mutation outcome resolver returned an invalid receipt",
  "CSF worker alert threshold reached",
  "Content report attempt metering failed",
  "Content report attempt metering returned an unusable row",
  "Content report origin resolution failed",
  "Content report submitted successfully",
  "Content report target lookup failed",
  "Content report transaction failed",
  "Content report transaction returned an unusable row",
  "Data export job completed",
  "Data export job failed",
  "Development email provider send blocked by safety policy",
  "Durable certificate delivery retry failed closed",
  "Email delivered via local Mailpit transport",
  "Email provider client could not be constructed",
  "Email render failed",
  "Email request cancelled before it reached the provider",
  "Email transport unavailable (set EMAIL_TRANSPORT=mailpit locally or configure RESEND_API_KEY)",
  "Email validation failed: No message body provided",
  "Exception while appending Google spreadsheet values",
  "Exception while batch reading Google spreadsheet values",
  "Exception while clearing Google spreadsheet values",
  "Exception while creating Google spreadsheet",
  "Exception while ensuring Google sheet tab",
  "Exception while fetching Google Drive file metadata",
  "Exception while fetching Google spreadsheet metadata",
  "Exception while reading Google Drive comment threads",
  "Exception while reading Google Sheets comment anchors",
  "Exception while reading Google spreadsheet acquisition evidence",
  "Exception while reading Google spreadsheet source values",
  "Exception while reading Google spreadsheet tab inventory",
  "Exception while sending email",
  "Exception while updating Google spreadsheet values",
  "Exception while verifying Turnstile token",
  "Failed to append Google spreadsheet values",
  "Failed to batch read Google spreadsheet values",
  "Failed to check existing admin notifications",
  "Failed to clear Google spreadsheet values",
  "Failed to complete a CSF personal calendar operation",
  "Failed to confirm CSF Google disconnect audit",
  "Failed to create Google sheet tab",
  "Failed to create Google spreadsheet",
  "Failed to disconnect the CSF Google connection",
  "Failed to fetch Google Drive file metadata",
  "Failed to fetch Google spreadsheet metadata",
  "Failed to fetch admin users",
  "Failed to fetch auth user during data export",
  "Failed to insert batched admin notification",
  "Failed to load a CSF member feed page",
  "Failed to load a CSF member stream page",
  "Failed to log moderation result to database",
  "Failed to mark export job as failed",
  "Failed to notify admin of flagged content",
  "Failed to notify admin of trusted member application",
  "Failed to notify admin of user report",
  "Failed to queue a CSF preview for construction recovery",
  "Failed to queue email for a saved CSF post",
  "Failed to rank CSF profile link suggestions",
  "Failed to read Google Drive comment threads",
  "Failed to read Google Sheets comment anchors",
  "Failed to read Google spreadsheet acquisition evidence",
  "Failed to read Google spreadsheet source values",
  "Failed to read Google spreadsheet tab inventory",
  "Failed to record CSF Google disconnect failure",
  "Failed to record post-email change history",
  "Failed to refresh CSF post surfaces after a saved change",
  "Failed to refresh CSF post surfaces after a saved follow-up change",
  "Failed to refresh a CSF point path",
  "Failed to resolve a CSF post mutation outcome",
  "Failed to retrieve user violations",
  "Failed to save CSF post images after the post was saved",
  "Failed to send email via Resend",
  "Failed to store a CSF announcement link preview",
  "Failed to update Google spreadsheet values",
  "Failed to update batched admin notification",
  "Failed to write data export audit event",
  "Google Drive returned an incomplete file metadata response",
  "Image moderation failed",
  "No admin users found to notify",
  "Resend accepted an email without returning a message identity",
  "Text moderation failed",
  "Turnstile secret key is not configured",
  "Turnstile verification failed",
  "Unexpected certificate resend failure",
  "Unexpected error in report-content API",
  "Unexpected volunteer-hours publication failure",
  "Unhandled server request failure",
  "Volunteer-hours email delivery claim failed",
  "Volunteer-hours email delivery settlement failed",
  "Volunteer-hours email dispatch threw",
  "Volunteer-hours email payload preparation failed",
  "Volunteer-hours publication committed",
  "Volunteer-hours publication committed without an email worker",
  "Volunteer-hours publication rejected",
  "Volunteer-hours publication returned an invalid receipt",
  "csf-sheet-writeback: failed to record attempt outcome",
]);
