-- Retired: this ad-hoc snippet embedded reusable organization join codes and
-- depended on whichever auth users happened to exist locally.
--
-- Deterministic fictional organizations and accounts are created by the
-- supported local fixture workflow (`bun run supabase:seed:local-dev`). SQL
-- loaded by `supabase db reset` belongs only in ../seeds/local-only.sql.
