-- AUD-042: plugin_data is server-only, including for objects created later.
--
-- Schema USAGE was already revoked from the browser roles, but the schema-scoped
-- default privileges still named `authenticated` for future tables, sequences,
-- and routines, so the next private-plugin migration would have re-granted it,
-- and `csf_stamp_application_policy_version` still carried PUBLIC/anon/
-- authenticated EXECUTE from the built-in default at creation time. This closes
-- the existing objects and those defaults, then proves the outcome on probe
-- objects before committing.
--
-- Enforced boundary: schema USAGE. PostgreSQL's built-in global default grants
-- EXECUTE on new functions to PUBLIC, and per ALTER DEFAULT PRIVILEGES the
-- per-schema form cannot revoke a globally granted default. Revoking EXECUTE
-- from PUBLIC globally for a shared owner role would reach far outside this
-- schema, and an event trigger is out of scope, so a future plugin_data
-- function will still carry the PUBLIC EXECUTE bit. Without schema USAGE that
-- bit is unreachable from anon/authenticated, which the probe below verifies by
-- actually calling as those roles rather than by reading the ACL alone.
--
-- service_role keeps schema USAGE so private plugin flows are unaffected.

BEGIN;

REVOKE ALL ON SCHEMA plugin_data FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA plugin_data
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA plugin_data
  FROM PUBLIC, anon, authenticated;
-- ROUTINES covers functions, aggregates, and procedures.
REVOKE ALL ON ALL ROUTINES IN SCHEMA plugin_data
  FROM PUBLIC, anon, authenticated;

GRANT USAGE ON SCHEMA plugin_data TO service_role;

DO $$
DECLARE
  owner_role text;
  uncovered_owner text;
BEGIN
  -- Every role that owns something here, plus whoever applies the ledger.
  -- Default privileges are recorded per creating role, so a role that is
  -- missed would keep re-granting the browser roles on its future objects.
  FOR owner_role IN
    SELECT DISTINCT role_name
    FROM (
      SELECT pg_catalog.pg_get_userbyid(namespace.nspowner) AS role_name
      FROM pg_catalog.pg_namespace AS namespace
      WHERE namespace.nspname = 'plugin_data'
      UNION
      SELECT pg_catalog.pg_get_userbyid(class.relowner)
      FROM pg_catalog.pg_class AS class
      JOIN pg_catalog.pg_namespace AS namespace
        ON namespace.oid = class.relnamespace
      WHERE namespace.nspname = 'plugin_data'
      UNION
      SELECT pg_catalog.pg_get_userbyid(routine.proowner)
      FROM pg_catalog.pg_proc AS routine
      JOIN pg_catalog.pg_namespace AS namespace
        ON namespace.oid = routine.pronamespace
      WHERE namespace.nspname = 'plugin_data'
      UNION
      SELECT CURRENT_USER::text
    ) AS owners(role_name)
    ORDER BY role_name
  LOOP
    IF NOT pg_catalog.pg_has_role(CURRENT_USER, owner_role, 'USAGE') THEN
      RAISE EXCEPTION
        'cannot close plugin_data default privileges for owner role %', owner_role;
    END IF;

    EXECUTE pg_catalog.format(
      'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA plugin_data '
      'REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated',
      owner_role
    );
    EXECUTE pg_catalog.format(
      'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA plugin_data '
      'REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated',
      owner_role
    );
    EXECUTE pg_catalog.format(
      'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA plugin_data '
      'REVOKE ALL ON ROUTINES FROM PUBLIC, anon, authenticated',
      owner_role
    );
  END LOOP;

  SELECT owners.role_name
  INTO uncovered_owner
  FROM (
    SELECT pg_catalog.pg_get_userbyid(class.relowner) AS role_name
    FROM pg_catalog.pg_class AS class
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = class.relnamespace
    WHERE namespace.nspname = 'plugin_data'
    UNION
    SELECT pg_catalog.pg_get_userbyid(routine.proowner)
    FROM pg_catalog.pg_proc AS routine
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = routine.pronamespace
    WHERE namespace.nspname = 'plugin_data'
  ) AS owners
  WHERE NOT pg_catalog.pg_has_role(CURRENT_USER, owners.role_name, 'USAGE')
  LIMIT 1;

  IF uncovered_owner IS NOT NULL THEN
    RAISE EXCEPTION
      'plugin_data owner % is outside the reviewed default privilege closure',
      uncovered_owner;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- Prove the closure on real objects, then remove the probe.
-- ---------------------------------------------------------------------------

CREATE TABLE plugin_data.default_acl_probe (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE plugin_data.default_acl_probe ENABLE ROW LEVEL SECURITY;

CREATE FUNCTION plugin_data.default_acl_probe_function()
RETURNS integer
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$ SELECT 1 $$;

DO $$
DECLARE
  client_role text;
  routine_is_reachable boolean;
  table_is_reachable boolean;
BEGIN
  FOREACH client_role IN ARRAY ARRAY['anon'::text, 'authenticated'::text]
  LOOP
    IF pg_catalog.has_schema_privilege(client_role, 'plugin_data', 'USAGE') THEN
      RAISE EXCEPTION '% retains plugin_data schema usage', client_role;
    END IF;

    IF pg_catalog.has_table_privilege(
      client_role, 'plugin_data.default_acl_probe', 'SELECT,INSERT,UPDATE,DELETE'
    ) THEN
      RAISE EXCEPTION '% inherits privileges on new plugin_data tables', client_role;
    END IF;

    IF pg_catalog.has_sequence_privilege(
      client_role, 'plugin_data.default_acl_probe_id_seq', 'USAGE,SELECT,UPDATE'
    ) THEN
      RAISE EXCEPTION '% inherits privileges on new plugin_data sequences', client_role;
    END IF;

    IF EXISTS (
      SELECT 1
      FROM pg_catalog.pg_proc AS routine
      CROSS JOIN LATERAL pg_catalog.aclexplode(routine.proacl) AS acl
      WHERE routine.oid = 'plugin_data.default_acl_probe_function()'::regprocedure
        AND acl.grantee = client_role::regrole
    ) THEN
      RAISE EXCEPTION
        '% is named directly in a new plugin_data routine grant', client_role;
    END IF;

    -- The enforced gate: no schema USAGE means no reachable object, whatever
    -- the built-in PUBLIC default put on the routine itself.
    routine_is_reachable := true;
    BEGIN
      EXECUTE pg_catalog.format('SET LOCAL ROLE %I', client_role);
      PERFORM plugin_data.default_acl_probe_function();
    EXCEPTION
      WHEN insufficient_privilege THEN routine_is_reachable := false;
    END;
    RESET ROLE;

    table_is_reachable := true;
    BEGIN
      EXECUTE pg_catalog.format('SET LOCAL ROLE %I', client_role);
      PERFORM 1 FROM plugin_data.default_acl_probe;
    EXCEPTION
      WHEN insufficient_privilege THEN table_is_reachable := false;
    END;
    RESET ROLE;

    IF routine_is_reachable THEN
      RAISE EXCEPTION '% can still call a new plugin_data routine', client_role;
    END IF;
    IF table_is_reachable THEN
      RAISE EXCEPTION '% can still read a new plugin_data table', client_role;
    END IF;
  END LOOP;
END;
$$;

DROP FUNCTION plugin_data.default_acl_probe_function();
DROP TABLE plugin_data.default_acl_probe;

-- ---------------------------------------------------------------------------
-- Fail closed on any residual browser-facing privilege or default
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_class AS class
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = class.relnamespace
    CROSS JOIN pg_catalog.unnest(ARRAY['anon'::text, 'authenticated'::text]) AS client(role_name)
    WHERE namespace.nspname = 'plugin_data'
      AND class.relkind IN ('r', 'p', 'v', 'm', 'f')
      AND pg_catalog.has_table_privilege(
        client.role_name, class.oid, 'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'
      )
  ) THEN
    RAISE EXCEPTION 'a browser role retains a plugin_data relation privilege';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_class AS class
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = class.relnamespace
    CROSS JOIN pg_catalog.unnest(ARRAY['anon'::text, 'authenticated'::text]) AS client(role_name)
    WHERE namespace.nspname = 'plugin_data'
      AND class.relkind = 'S'
      AND pg_catalog.has_sequence_privilege(client.role_name, class.oid, 'USAGE,SELECT,UPDATE')
  ) THEN
    RAISE EXCEPTION 'a browser role retains a plugin_data sequence privilege';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_proc AS routine
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = routine.pronamespace
    CROSS JOIN pg_catalog.unnest(ARRAY['anon'::text, 'authenticated'::text, 'public'::text])
      AS client(role_name)
    WHERE namespace.nspname = 'plugin_data'
      AND pg_catalog.has_function_privilege(client.role_name, routine.oid, 'EXECUTE')
  ) THEN
    RAISE EXCEPTION 'a browser role retains plugin_data routine execution';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_default_acl AS default_acl
    JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.oid = default_acl.defaclnamespace
    CROSS JOIN LATERAL pg_catalog.aclexplode(default_acl.defaclacl) AS acl
    LEFT JOIN pg_catalog.pg_roles AS grantee ON grantee.oid = acl.grantee
    WHERE namespace.nspname = 'plugin_data'
      AND (acl.grantee = 0 OR grantee.rolname IN ('anon', 'authenticated'))
  ) THEN
    RAISE EXCEPTION 'plugin_data retains browser-facing default privileges';
  END IF;

  IF NOT pg_catalog.has_schema_privilege('service_role', 'plugin_data', 'USAGE') THEN
    RAISE EXCEPTION 'service_role lost plugin_data schema usage';
  END IF;
END;
$$;

COMMIT;
